Initial routing for segments and rrenaming modules to segments
Osedea/akufen_iCanChange_react-native pull request #21
Opened 2021-01-05 19:23 UTC by AugustGit

## What's in this PR
Investigating how to do the routing

![Screen Shot 2021-01-05 at 2 21 24 PM](https://user-images.githubusercontent.com/15388286/103689610-90852900-4f61-11eb-8ad9-3930cf3568bd.png)

## Prerequisites

- [ ] Documentation
- [ ] Tests added

- [ ] Jest tests passed (and nothing in red!)
- [ ] Detox tests passed
- [ ] PR & Commit Title and Message are formatted according to [Osedea Guidelines](https://github.com/Osedea/osedea_project_coding-standards/tree/master/git)
- [ ] Ready to Merge

## Usage

## Design Changelog

Design | iOS | Android
--- | --- | ---
![]() | ![]() | ![]()

## Notes for Reviewers

2021-01-05 22:24 UTC, Helen2hang commented on src/components/ElementProgressBar.tsx
> +    }
instead of the loop, you can use
```
    const sections = [...Array(totalElements).keys()]
```

2021-01-05 22:44 UTC, Helen2hang requested changes

2021-01-05 22:44 UTC, Helen2hang commented on src/components/ElementProgressBar.tsx
> +                                pageMargin -
Can we change the `pageMargin` to SLIGHTLY_BIGGER *2 directly since i think almost everypage with the progress bar will have the slightlyBigger as padding.
Therefore, we can remove `pageMargin` as a props so that in the future we don't need to pass pageMargin everytime we use the ElementProgressBar.

2021-01-05 22:44 UTC, Helen2hang commented on src/pages/download/VideoDownloadPage.tsx
> +                    // onPress={() => reset(STACKS.MAIN_STACK.LOGIN.LOG_IN_PAGE)}
can you put it back to login page?

2021-01-05 22:44 UTC, Helen2hang commented on src/pages/elements/EndSegmentPage.tsx
> +                pageMargin={2 * SLIGHTLY_BIGGER_PADDING_HORIZONTAL}
can be removed after we put the SLIGHTLY_BIGGER * 2 as pageMargin directly in ElementProgressBar.

2021-01-05 22:44 UTC, Helen2hang commented on src/components/ElementProgressBar.tsx
> +                        height={3}
Create a `const ELEMENT_PROGRESS_BAR = 3` in this file.

2021-01-05 22:44 UTC, Helen2hang commented on src/pages/elements/IntroductionPage.tsx
> +                    title={headerTitle}
can the headerTitle be taken from the translation file using the section and segment like we do for all the other text instead of passing it as a params?

2021-01-05 22:53 UTC, AugustGit commented on src/pages/elements/IntroductionPage.tsx
> +                    title={headerTitle}
Those are `const` for now but they will come from the params when we need to use the routing to get those values

2021-01-05 22:58 UTC, Helen2hang commented
for the navigation i think it the alternative branching should be inside the segmentType itself instead of in the segment level 🤔  maybe?

For example 
```javascript
export const Navigation_Routes = {
    [JourneySection.SECTION_ONE]: {
        [SectionOneSegment.SEGMENT_1]: {
               {
                [SegmentType.INTRO]: {
                    next: STACKS.MAIN_STACK.ELEMENTS.QUIZ,
                    next2: STACKS.MAIN_STACK.ELEMENTS.altQUIZ,
                    previous: STACKS.MAIN_STACK.SECTION_ONE
                },
                [SegmentType.QUIZ]: {
                    next: STACKS.MAIN_STACK.ELEMENTS.END_SEGMENT,
                    previous: STACKS.MAIN_STACK.ELEMENTS.INTRODUCTION_PAGE
                },
                [SegmentType.altQUIZ]: {
                    next: STACKS.MAIN_STACK.ELEMENTS.END_SEGMENT,
                    previous: STACKS.MAIN_STACK.ELEMENTS.INTRODUCTION_PAGE
                }
            },
    }
};

``` 

and then lets say theres two button
```
<button onPress={setAnswer(CHOISE_ONE)}> Choice one </button>
<button onPress={setAnswer(CHOICE_TWO)}> Choice two </button>
```
and then 
```javascript
const submit =() =>{
if(answer===CHOICE_TWO){
      push(Navigation_Routes[section][segment][routeswitch][SegmentType.INTRO].next2}
else{
      push(Navigation_Routes[section][segment][routeswitch][SegmentType.INTRO].next)
}
```

Something like that.
What do you think @gnoriega27  @AugustGit ?

2021-01-05 23:11 UTC, Helen2hang commented on src/components/ElementProgressBar.tsx
> +                                pageMargin -
nvm i think we can do it like this instead
```javascript
const BARS_MARGIN_LEFT = 2;


<Container
width={ (Dimensions.get('window').width /totalElements) - (BARS_MARGIN_LEFT * totalElements -1) }
marginLeft={BARS_MARGIN_LEFT}
>

</Container>
```

2021-01-05 23:13 UTC, Helen2hang commented on src/pages/elements/IntroductionPage.tsx
> +                    title={headerTitle}
Can't we just do it like this:
```javascript
<HeaderNavigation
title={t('${section}.${segment}.introduction.headerTitle')}
/>
```

2021-01-06 14:46 UTC, gnoriega27 commented on src/components/ElementProgressBar.tsx
> +const ElementProgressBar: React.FC<IProps & Style> = ({
So each element manages its progress?

2021-01-06 15:03 UTC, gnoriega27 approved these changes

2021-01-06 15:40 UTC, AugustGit commented on src/components/ElementProgressBar.tsx
> +const ElementProgressBar: React.FC<IProps & Style> = ({
We need it here since it has to be able to scroll with the rest of the page

2021-01-06 16:46 UTC, Helen2hang commented on src/pages/elements/IntroductionPage.tsx
> +}
we can remove this since we won't be using it anymore

2021-01-06 16:46 UTC, gnoriega27 approved these changes

2021-01-06 16:46 UTC, Helen2hang commented on src/pages/elements/EndPage.tsx
> +                            params: { headerTitle: t(`${section}.${segment}.cardheader`) },
Can remove the params here

2021-01-06 16:48 UTC, Helen2hang commented on src/pages/elements/EndPage.tsx
> +}
can remove this too

2021-01-06 16:49 UTC, Helen2hang commented on src/pages/elements/EndPage.tsx
> +                    title={headerTitle}
use the same headerTitle version as IntroductionPage

2021-01-06 16:49 UTC, AugustGit commented on src/pages/elements/EndPage.tsx
> +                            params: { headerTitle: t(`${section}.${segment}.cardheader`) },
I removed the headerTitle, I left the params as we will need it to pass routeSwitch eventually

2021-01-06 16:51 UTC, Helen2hang approved these changes

2021-01-06 16:57 UTC, merged