Added types, constants and assets
Osedea/akufen_iCanChange_react-native pull request #4
Opened 2020-12-21 22:56 UTC by AugustGit

## What's in this PR

Static Elements, Fonts, Styles, Types, Translations

## Prerequisites

- [ ] Documentation
- [ ] Tests added

- [ ] Jest tests passed (and nothing in red!)
- [ ] Detox tests passed
- [ ] PR & Commit Title and Message are formatted according to [Osedea Guidelines](https://github.com/Osedea/osedea_project_coding-standards/tree/master/git)
- [ ] Ready to Merge

## Usage

## Design Changelog

Design | iOS | Android
--- | --- | ---
![]() | ![]() | ![]()

## Notes for Reviewers

2020-12-21 22:59 UTC, Helen2hang requested changes

2020-12-21 22:59 UTC, Helen2hang commented on src/constants/global-styles.ts
> +});
Please follow the Zeplin naming
![image](https://user-images.githubusercontent.com/25255911/102829932-30658300-43b6-11eb-9fdf-d7cf62f7ab1e.png)

2020-12-22 19:08 UTC, AugustGit commented on src/constants/global-styles.ts
> +});
no but they are sizes in the Invision that we need to use, the Zeplin in incomplete

2020-12-22 20:29 UTC, Helen2hang requested changes
Good work!! However a few changes to be made.

2020-12-22 20:29 UTC, Helen2hang commented on src/components/DotLineProgress.tsx
> +                    borderColor={lineStart ? colors.green_100 : colors.black}
i don't think we can put the color to green_100 because the background will change color. Have you tried transparent?

2020-12-22 20:29 UTC, Helen2hang commented on src/components/DotLineProgress.tsx
> +                backgroundColor={status === EStatus.LOCKED ? lockedColor : colors.black}
For the locked color, i think its transparent white by default.
so you can remove lockedColor from the props and put colors.transparentWhite here.

2020-12-22 20:29 UTC, Helen2hang commented on src/components/DotLineProgress.tsx
> +                    borderColor={lineEnd ? colors.green_100 : colors.black}
same with transparent.

2020-12-22 20:29 UTC, Helen2hang commented on src/components/generic/BasicCard.tsx
> +    const { children, locked, lockedColor, style, ...rest } = props;
Instead of having `locked` and `lockedColor` we can put `backgroundColor?:string` in the props since not all the cards will be using the locking mechanism.
and inside here `const { children, locked, backgroundColor=colors.white, style, ...rest } = props;` so that we have the white background card by default. Instead of BasicCard wie can call it RoundedCard.

2020-12-22 20:29 UTC, Helen2hang commented on src/pages/section/SectionOnePage.tsx
> +                        lockedColor={colors.green_50}
here we with the requested change, you can just put `backgroundColor ={ status === EStatus.LOCKED? colors.transparentWhite : colors.white }`
Transparent white since the background color of the whole app will change color.

2020-12-22 20:29 UTC, Helen2hang commented on src/pages/section/SectionOnePage.tsx
> +                    </BasicCard>
I think we need to create another component called ModuleCard that will use Basic card just as you did since it will be used in Section1Card in the journey tab.

2020-12-22 20:29 UTC, Helen2hang commented on src/types/section/index.ts
> +export enum EStatus {
I don't wanna sound picky but can we remove the E in front of the enums name XD? When i first got on CHAMPS project, i didn't understand why there was an E in front of everything.

2020-12-22 20:37 UTC, AugustGit commented on src/components/DotLineProgress.tsx
> +                    borderColor={lineStart ? colors.green_100 : colors.black}
that was suppose to be locked color good catch...i added it after

2020-12-22 20:41 UTC, Helen2hang commented on src/assets/locales/en/translation.json
> +    "sectionOne": {
Capital letter for SectionOne

2020-12-22 20:42 UTC, Helen2hang commented on src/assets/locales/fr/translation.json
> +    "sectionOne": {
Capital letter

2020-12-22 21:24 UTC, AugustGit commented on src/assets/locales/en/translation.json
> +    "sectionOne": {
it will be used called with a variable sometimes though

2020-12-22 21:24 UTC, AugustGit commented on src/assets/locales/en/translation.json
> +    "sectionOne": {
${section}.${module}.title

2020-12-22 21:33 UTC, Helen2hang commented on src/assets/locales/en/translation.json
> +    "sectionOne": {
okie

2020-12-22 21:46 UTC, Helen2hang commented on src/pages/section/SectionOnePage.tsx
> +                    </BasicCard>
@AugustGit  I think we can put this into a reusable ModuleCard component.

2020-12-22 21:55 UTC, AugustGit commented on src/pages/section/SectionOnePage.tsx
> +                    </BasicCard>
The size if the labels inside is different and it will never be locked or completed so I would have it be separate

2020-12-22 21:58 UTC, Helen2hang commented on src/pages/section/SectionOnePage.tsx
> +                    </BasicCard>
okiedokie

2020-12-22 21:59 UTC, Helen2hang approved these changes

2020-12-22 22:02 UTC, merged