Added ContactIntervenantPopup component (ICC-42)
Osedea/akufen_iCanChange_react-native pull request #5
Opened 2020-12-22 23:16 UTC by Helen2hang

## What's in this PR
Added the SectionOnePage to the JourneyStack since it contains the tabbar as well.
Fixed Page wrapper not scrolling.
The padding of the tabbar will need to take the color of the app but for now will leave it like this.

![ContactIntervenant](https://user-images.githubusercontent.com/25255911/102941832-aa167300-4481-11eb-991e-05d55e04a3a0.gif)

## Prerequisites

- [ ] Documentation
- [ ] Tests added

- [ ] Jest tests passed (and nothing in red!)
- [ ] Detox tests passed
- [ ] PR & Commit Title and Message are formatted according to [Osedea Guidelines](https://github.com/Osedea/osedea_project_coding-standards/tree/master/git)
- [ ] Ready to Merge

## Usage

## Design Changelog

Design | iOS | Android
--- | --- | ---
![]() | ![]() | ![]()

## Notes for Reviewers

2020-12-22 23:26 UTC, AugustGit commented on src/pages/journeyTab/JourneyTab.tsx
> +            <TitleWithCallIntervenantButton text={t('JourneyTab.hi', { userName: 'Marion' })} />
Just a note when we hardcode things that need to be changed we should flag them with a  // TODO etc...otherwise we might miss them later and it won't necessarily look wrong in the app

2020-12-22 23:26 UTC, AugustGit commented on src/pages/profileTab/ProfileTab.tsx
>                  <Label>Profile Tab</Label>
Hardcoded?

2020-12-22 23:29 UTC, AugustGit approved these changes

2020-12-22 23:31 UTC, AugustGit commented on src/components/ModuleStatusBox.tsx
> +                {t(`globalStyles.${status}`)}
{t(`Global.${status}`)} is correct here it is a Glocal element in the translation file

2020-12-22 23:32 UTC, AugustGit requested changes
Just one "globalStyles" needs to revert back to "Global"

2020-12-23 15:10 UTC, Helen2hang commented on src/pages/journeyTab/JourneyTab.tsx
> +            <TitleWithCallIntervenantButton text={t('JourneyTab.hi', { userName: 'Marion' })} />
okiedokie!

2020-12-23 15:11 UTC, Helen2hang commented on src/components/ModuleStatusBox.tsx
> +                {t(`globalStyles.${status}`)}
oops! thats my bad!

2020-12-23 15:30 UTC, AugustGit approved these changes

2020-12-23 15:34 UTC, merged